### ISSUE TITLE
build_ffmpeg_proxies.py requirements for video convertion 

### ISSUE THREAD

**Issue by lalupamiope** [GDquest/Blender-power-sequencer#168]
Hello. I was getting this error when I tried the proxies builder script over some mkv and mov files in a directory. 

```
scripts|master⚡ ⇒ python build_ffmpeg_proxies.py ~/Pictures/prueba 
Traceback (most recent call last):
  File "build_ffmpeg_proxies.py", line 237, in <module>
    media_objects.append(Video(path))
  File "build_ffmpeg_proxies.py", line 90, in __init__
    self.frame_count = self.get_frame_count(self.path_source)
  File "build_ffmpeg_proxies.py", line 101, in get_frame_count
    return int(subprocess.check_output(ffprobe_frame_cmd).decode())
ValueError: invalid literal for int() with base 10: 'N/A\n'
```

Then I converted them to mp4 with HandBrake (using _Fast 1080p30_ preset, and changed extension from .m4v to .mp4) and they worked. Which are the critical parameters that the video files need to comply with in order to work with the script?

If it helps, this is the ffmpeg version installed:

```
scripts|master⚡ ⇒ ffmpeg -version
ffmpeg version 2.8.14-0ubuntu0.16.04.1 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 5.4.0 (Ubuntu 5.4.0-6ubuntu1~16.04.9) 20160609
configuration: --prefix=/usr --extra-version=0ubuntu0.16.04.1 --build-suffix=-ffmpeg --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --cc=cc --cxx=g++ --enable-gpl --enable-shared --disable-stripping --disable-decoder=libopenjpeg --disable-decoder=libschroedinger --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-librtmp --enable-libschroedinger --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxvid --enable-libzvbi --enable-openal --enable-opengl --enable-x11grab --enable-libdc1394 --enable-libiec61883 --enable-libzmq --enable-frei0r --enable-libx264 --enable-libopencv
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libavresample   2.  1.  0 /  2.  1.  0
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100

```

**Comment by NathanLovato** [comment]
Do you have ffprobe installed as well? It's required for this program to work. On windows, it typically comes with ffmpeg, maybe not on Linux? The video editor I work with uses Linux/Solus but I typically generate the proxies for him.

**Comment by sudopluto** [comment]
ffprobe is installed, it just can't get the frame count from the original file, and thus returns N/A. Hmm. Idk how to fix this, besides just added a check for a failure. It's just used for progress indication, nothing critical functionality wise.

**Comment by sudopluto** [comment]
Perhaps this could be rolled into an update to add the progress bar? / (Modularize it)

Sorry for letting a bug like this occurr in the first place, should have thought about edge cases.

**Comment by NathanLovato** [comment]
> Perhaps this could be rolled into an update to add the progress bar? / (Modularize it)

Yeah, so razvan is pretty much done with the multithread script rewrite, done in a functional style - It uses tqdm to display a progress bar, and it has some nice code to pipe commands. Maybe we can reuse the idea and some of the code? What do you think @razvanc (context: this is the script to build proxies with ffmpeg - lighter, faster than blender, + support for transparent image proxies)?

> Sorry for letting a bug like this occurr in the first place, should have thought about edge cases.

Hey no worries, any piece of software needs a lot of testing to catch these!

**Comment by sudopluto** [comment]
@lalupamiope tried a stab at a hotfix, could you test this out?

https://raw.githubusercontent.com/sudopluto/Blender-power-sequencer/hotfix-proxy-script/scripts/build_ffmpeg_proxies.py

-----------------------

basically if ffprobe cant get the frame count, then framecount is set to -1. then the progress indicator
makes sure that the frame count is not -1 before trying to output progress.

**Comment by alopatindev** [comment]
How about using [`mediainfo`](https://stackoverflow.com/questions/2017843/fetch-frame-count-with-ffmpeg/28376817#28376817) instead? Works for me:

```patch
--- scripts/build_ffmpeg_proxies.py.orig	2018-08-31 18:29:47.559670332 +0300
+++ scripts/build_ffmpeg_proxies.py	2018-09-01 23:42:29.271593512 +0300
@@ -64,19 +64,12 @@
         """
         takes in path to file, returns the number of frames in the video
         """
-        ffprobe_frame_cmd = [
-            "ffprobe",
-            "-v",
-            "error",
-            "-select_streams",
-            "v:0",
-            "-show_entries",
-            "stream=nb_frames",
-            "-of",
-            "default=noprint_wrappers=1:nokey=1",
+        mediainfo_frame_cmd = [
+            'mediainfo',
+            '--Output=Video;%FrameCount%',
             path,
         ]
-        return int(subprocess.check_output(ffprobe_frame_cmd).decode())
+        return int(subprocess.check_output(mediainfo_frame_cmd).decode())
 
     def get_path_proxy(self, path):
         """
```
