### ISSUE TITLE
The toolbar menu is missing

### ISSUE THREAD

**Issue by aditiapratama** [GDquest/Blender-power-sequencer#249]
I tried to pull today from latest master and it seems the menu toolbar is missing.

here's the log from console
```
Registered Power Sequencer with 62 modules
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
AttributeError: 'NoneType' object has no attribute 'active_strip'

location: <unknown location>:-1

location: <unknown location>:-1
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
rna_uiItemO: operator missing srna 'power_sequencer.batch_transcode'

C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\ui\panel.py:55
```

**Comment by NathanLovato** [comment]
Your repo is not up to date. Are you not using your own fork or working on a different git branch?

```
Registered Power Sequencer with 62 modules
```

-> There are 69 modules on master

![image](https://user-images.githubusercontent.com/12694995/45816925-11c83b80-bd18-11e8-84b9-9b742425679c.png)

```
Traceback (most recent call last):
  File "C:\Users\aditi\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Blender-power-sequencer\operators\crossfade_add.py", line 38, in poll
    active = bpy.context.scene.sequence_editor.active_strip
```
This line doesn't exist anymore either. Please re-download the master version if your install got messed up

**Comment by aditiapratama** [comment]
ah my bad, after [syncing the fork](https://help.github.com/articles/syncing-a-fork/) I get this all working again. 

Thank you
