### ISSUE TITLE
Markers as timecodes not working on Solus

### ISSUE THREAD

**Issue by guilhermehto** [GDquest/Blender-power-sequencer#356]
When trying to use the operator, here's the error I get:
```
Traceback (most recent call last):
  File "/home/guilherme/programs/blender/2.80/scripts/addons/Blender-power-sequencer/operators/markers_as_timecodes.py", line 44, in execute
    pyperclip.copy('\n'.join(markers_as_timecodes))
  File "/home/guilherme/programs/blender/2.80/scripts/addons/Blender-power-sequencer/operators/utils/pyperclip/__init__.py", line 612, in lazy_load_stub_copy
    return copy(text)
  File "/home/guilherme/programs/blender/2.80/scripts/addons/Blender-power-sequencer/operators/utils/pyperclip/__init__.py", line 297, in __call__
    raise PyperclipException(EXCEPT_MSG)
Blender-power-sequencer.operators.utils.pyperclip.PyperclipException: 
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.io/en/latest/introduction.html#not-implemented-error 

location: <unknown location>:-1

```

**OS:** Solus 4.0 Fortitude

**Comment by NathanLovato** [comment]
You need to have either xclip or xsel installed on linux to copy to the clipboard. Look for either command in your package manager.

**Comment by guilhermehto** [comment]
Installed xclip and it worked, thanks!
