### ISSUE TITLE
NVENC option on mobile GPU

### ISSUE THREAD

**Issue by dvsie** [GDquest/Blender-power-sequencer#416]
Hi. I have Windows 10, **bpsproxy-0.1.3**, Python.3.7_3.7.1264.0_x64. Notebook with Nvidia GT730M card. CUDA in blender 2.80 work fine. bpsproxy successfully work with cpu, but when use **-p nvenc** I see error.

_..so while type this msg I've search and find that **NVENC is hardware feature** and now I think that **-p nvenc** option not work for GTXXX and similar. And here is a GPU's _[matrix](https://developer.nvidia.com/video-encode-decode-gpu-support-matrix)_

Or may be I need configure ffmpeg or python somehow to use my GPU?

That's from cmd:
`C:\Users\User>python -m bpsproxy C:\Users\User\Desktop\test -s 25 50 100 -p nvenc

» Creating directories if necessary...

» Checking for existing proxies...
100%|██████████████████████████████████████████████████████████████████████████████████| 1/1 [00:01<00:00,  1.48s/file]

» Processing...
  0%|                                                                                          | 0/1 [00:00<?, ?file/s]Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 142, in <module>
    main()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\__main__.py", line 128, in main
    call(C, clargs, cmds=cmds, **kwargs)
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in call
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 75, in <listcomp>
    return [p.stdout for p in ps]
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\tqdm\std.py", line 1081, in __iter__
    for obj in iterable:
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\bpsproxy\call.py", line 72, in <lambda>
    ps = tqdm(map(lambda cmd: sp.run(cmd[1], **kwargs_s), cmds[1]),
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1264.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 487, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ffmpeg', '-y', '-v', 'quiet', '-stats', '-i', 'C:\\Users\\User\\Desktop\\test\\IMG_0823.MOV', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.25:ih*0.25', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_25.avi', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*0.5:ih*0.5', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_50.avi', '-pix_fmt', 'yuv420p', '-g', '1', '-sn', '-an', '-vf', 'colormatrix=bt601:bt709', '-vf', 'scale=iw*1.0:ih*1.0', '-c:v', 'h264_nvenc', '-qp', '25', '-preset', 'fast', 'C:\\Users\\User\\Desktop\\test\\BL_proxy\\IMG_0823.MOV\\proxy_100.avi']' returned non-zero exit status 1.
  0%|                                                                                          | 0/1 [00:01<?, ?file/s]`

**Comment by NathanLovato** [comment]
It depends on the graphics card yes, not all nvidia cards support nvenc. I'm not the one to ask there, you'll have to search for the info online.

You also must use a version of ffmpeg compiled with nvenc support. You can list available codecs from ffmpeg with this command:

```ffmpeg -codecs```

And to filter the list and find nvenc-compatible codecs, use something like

```ffmpeg -codecs | grep nvenc```

Or on Powershell, this should work:

```ffmpeg -codecs | Select-String nvenc```

**Comment by dvsie** [comment]
**PS C:\Windows\system32> ffmpeg -codecs | Select-String nvenc**
```ffmpeg version N-95004-g2f87c9f646 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20190918
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-ffnvcodec --enable-cuvid --enable-d3d11va **--enable-nvenc** --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt --enable-amf
  libavutil      56. 35.100 / 56. 35.100
  libavcodec     58. 58.101 / 58. 58.101
  libavformat    58. 33.100 / 58. 33.100
  libavdevice    58.  9.100 / 58.  9.100
  libavfilter     7. 58.102 /  7. 58.102
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100

 DEV.LS h264                 H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10 (decoders: h264 h264_qsv h264_cuvid ) (encoders:
 libx264 libx264rgb h264_amf **h264_nvenc** h264_qsv **nvenc nvenc_h264** )
 DEV.L. hevc                 H.265 / HEVC (High Efficiency Video Coding) (decoders: hevc hevc_qsv hevc_cuvid ) (encoder
s: libx265 **nvenc_hevc** hevc_amf **hevc_nvenc** hevc_qsv )
```

**Comment by dvsie** [comment]
```
Codecs:
 D..... = Decoding supported
 .E.... = Encoding supported
 ..V... = Video codec
 ..A... = Audio codec
 ..S... = Subtitle codec
 ...I.. = Intra frame-only codec
 ....L. = Lossy compression
 .....S = Lossless compression

```
I guess it not enough for correct work..
And I think it possible for CUDA considering that blender use it..

**-p mp4** is good enough if compare with blender original proxy..

So if no help for that isue You can close it. Thank you.

**Comment by NathanLovato** [comment]
You have the h264 nvenc codec but I don't know why it's not working and the regular mp4 is.
